#ifndef S21_FRONT_DEFINES_H_
#define S21_FRONT_DEFINES_H_

#define INPUT_CD 50

#define STATS_FINAL_COLOR_INDEX MAX_LEVEL
#define BACKGROUND_COLOR_INDEX (STATS_FINAL_COLOR_INDEX + 1)

#define OVERLAY_OFFSET 2
#define LEFT_PADDING 10
#define UP_PADDING 2

#define MATRIX_CHAR ' '
#define MATRIX_EMPTY ' '

#define DEFAULT_MENU_WIDTH 40
#define DEFAULT_MENU_HEIGHT 10

#define EXIT_SLEEP_TIME 3000

#endif  // S21_FRONT_DEFINES_H_